### ISSUE TITLE
Response header return normal content-type

### ISSUE THREAD

**Issue by sasurau4** [cloudflare/binast-cf-worker#1]
## Overview

I found the server returns js as `application/javascript` content-type, so I couldn't try binaryAST.

![D3___React_Examples](https://user-images.githubusercontent.com/13580199/58701086-efc1a580-83dc-11e9-98c1-1d2bb7fca724.png)

**Comment by xtuc** [comment]
Would it be possible to try deploying in your zone on Cloudflare's Worker? I suspect an internal configuration to interfer with that zone.

**Comment by xtuc** [comment]
This should be fixed now.

**Comment by sasurau4** [comment]
@xtuc I confirmed fixing. Thanks for fixing. 👍
